# Generated by Django 2.2 on 2021-04-07 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_id_to_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individual',
            options={'ordering': ('last_modified', 'created_at')},
        ),
    ]
